from typing import Union
from xrpl.models.deposit_preauth_entry_deposit_preauth_one_of import DepositPreauthEntryDepositPreauthOneOf

DepositPreauthEntryDepositPreauth = Union[DepositPreauthEntryDepositPreauthOneOf, str]

