"""
Legacy link proof module.

The standalone linkage proof functions (mpt_get_amount_linkage_proof,
mpt_get_balance_linkage_proof) have been removed from the mpt-crypto
utility layer. Their functionality is now integrated into the compact
AND-composed sigma proofs generated by:
  - mpt_get_confidential_send_proof (for amount + balance linkage)
  - mpt_get_convert_back_proof (for balance linkage)

This module is retained for backward compatibility but the functions
below are no longer functional with the latest mpt-crypto library.
"""
